spring:
  application:
    name: metablock-web
  
  # Thymeleaf 설정
  thymeleaf:
    cache: false # 개발 시 캐시 비활성화
    encoding: UTF-8
    mode: HTML
    prefix: classpath:/templates/
    suffix: .html
  
  # Cache 설정
  cache:
    type: simple
  
  # H2 데이터베이스 설정
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: 
  
  h2:
    console:
      enabled: true # H2 콘솔 활성화 (http://localhost:8080/h2-console)
  
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true

# CMS 설정
cms:
  api:
    url: http://localhost:3001/api
  cache:
    ttl: 300 # 5분

# 서버 설정
server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

# 로깅 설정
logging:
  level:
    com.example.metablock: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG 